### ISSUE TITLE
deploy 在 Windows 上不成功

### ISSUE THREAD

**Issue by navono** [nagaame/drone-golang-example#1]
```
 - name: deploy
    image: appleboy/drone-ssh
    pull: true
    settings:
      host: example.me
      user: root
      key:
        from_secret: deploy_key
      script:
        - cd /data
        - mkdir app/
        - cd /data/app
        - docker rmi -f example/demo
        - echo "login docker"
        - echo "login success, pulling..."
        - docker pull example/demo:latest
        - echo "image running"
        - docker run -p 8088:8088 -d example/demo
        - echo "run success"
```
我在 `win10` 上使用上面的配置，因为 docker 没有登录而导致 pull 失败，之后我又加上了
```
docker login 10.30.26.86:8888 --username ping --password Ping12345
```
没成功。
接着有尝试不直接使用 docker 命令，而使用 `docker-compose`，但是执行完，同样没有启动 docker 的运行实例。
